### ISSUE TITLE
Update docs around `import('rewiremock/webpack/interceptor')`

### ISSUE THREAD

**Issue by alexflorisca** [theKashey/rewiremock#36]
What's this file used for and where should it be imported into if someone gets `Cannot read property 'call' of undefined` errors?

**Comment by theKashey** [comment]
See #6, that `call` problem should be fixed in 3.7.5+ versions.
(and it is for webpack, and injected by loader)

**Comment by alexflorisca** [comment]
@theKashey I'm using webpack 4.12.1 and I still get that error when including `rewiremock/webpack/plugin` in my webpack config. I've got the other plugins in there as well and nada. Any thoughts?

**Comment by theKashey** [comment]
Could share the code, which generates this error?

**Comment by alexflorisca** [comment]
Sure thing..

This is the repo and branch I'm working on https://github.com/Financial-Times/n-ui/tree/fix-ads-tests

I found that simply adding `new (require('rewiremock/webpack/plugin'))()` to the webpack `plugins` options gives this error:

```
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR
  {
    "message": "Uncaught TypeError: Cannot read property 'call' of undefined\nat webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30\n\nTypeError: Cannot read property 'call' of undefined\n    at __webpack_require__ (webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30)\n    at fn (webpack:///webpack/bootstrap:101 <- browser/bundles/o-errors/test/filter-error.spec.js:102:20)\n    at Object../browser/bundles/o-errors/test/filter-error.spec.js (browser/bundles/o-errors/test/filter-error.spec.js:832:32)\n    at __webpack_require__ (webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30)\n    at ./browser/bundles/o-errors/filter-error.js.module.exports (webpack:///webpack/bootstrap:791 <- browser/bundles/o-errors/test/filter-error.spec.js:792:90)\n    at browser/bundles/o-errors/test/filter-error.spec.js:795:10",
    "str": "Uncaught TypeError: Cannot read property 'call' of undefined\nat webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30\n\nTypeError: Cannot read property 'call' of undefined\n    at __webpack_require__ (webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30)\n    at fn (webpack:///webpack/bootstrap:101 <- browser/bundles/o-errors/test/filter-error.spec.js:102:20)\n    at Object../browser/bundles/o-errors/test/filter-error.spec.js (browser/bundles/o-errors/test/filter-error.spec.js:832:32)\n    at __webpack_require__ (webpack:///webpack/bootstrap:724 <- browser/bundles/o-errors/test/filter-error.spec.js:725:30)\n    at ./browser/bundles/o-errors/filter-error.js.module.exports (webpack:///webpack/bootstrap:791 <- browser/bundles/o-errors/test/filter-error.spec.js:792:90)\n    at browser/bundles/o-errors/test/filter-error.spec.js:795:10"
  }
```

I'm using karma to run the test files. The webpack setup for it is a bit long winded with loads of merged config files, but essentially this line brings in and merges 3 config files: https://github.com/Financial-Times/n-ui/blob/fix-ads-tests/karma.conf.js#L22

The one I'm using to test rewiremock is this: https://github.com/Financial-Times/n-ui/blob/fix-ads-tests/build/webpack/test.js

All webpack things live here: https://github.com/Financial-Times/n-ui/tree/fix-ads-tests/build/webpack

If you could shed some light on this I would very much appreciate it. Thanks.

**Comment by theKashey** [comment]
I've tracked down the problem, and it __was__ described in the docs. But even I forgot about it.

You have to `import('rewiremock/webpack/interceptor')` somewhere, to actually have this module available.

https://github.com/theKashey/rewiremock#webpack-troubleshooting - second case


>TypeError: Cannot read property 'call' of undefined
>Caused by webpack. Sometimes is does not include some important files. To solve this problem just import('rewiremock/webpack/interceptor') in scaffolding. The problem is simply - this file does not exists in the bundle.

```require('rewiremock/webpack/interceptor');```
I've added ^this^ into one of your tests, and everything is green

<img width="520" alt="screen shot 2018-08-16 at 10 44 11 pm" src="https://user-images.githubusercontent.com/582410/44209310-6c64f980-a1a6-11e8-9537-f644403ab760.png">
